# Generated by Django 3.1.7 on 2021-03-19 16:17

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=4)),
                ('date', models.DateField()),
                ('price', models.IntegerField(verbose_name=builtins.max)),
            ],
        ),
    ]
